# Generated by Django 4.1.4 on 2023-01-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagine", "0007_alter_post_image_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
